version: '3.1'

services:

  bookmedik:
    image: nginx:latest
    container_name: servidor_bookmedik
    restart: always
    ports:
      - 80:80
    volumes:
      - ../build3/bookmedik_origin:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
  
  php:
    image: manuellora/bookmedik:v1
    container_name: php-fpm
    restart: always
    environment:
      USER: bookmedik
      PASSWORD: bookmedik
      HOST: db
      DB: bookmedik
    volumes:
      - ../build3/bookmedik_origin:/var/www/html
  
  db:
    image: mariadb
    container_name: servidor_mysql
    restart: always
    environment:
      MYSQL_DATABASE: bookmedik
      MYSQL_USER: bookmedik
      MYSQL_PASSWORD: bookmedik
      MYSQL_ROOT_PASSWORD: bookmedik
    volumes:
      - /media/manuel/Datos1/Docker/bookmedik/volmaria:/var/lib/mysql

